server:
    # 端口号 
    port: 8080
    
spring: 
    # redis配置 
    redis:
        # Redis数据库索引（默认为0）
        database: 0
        # Redis服务器地址
        host: 127.0.0.1
        # Redis服务器连接端口
        port: 6379
        # Redis服务器连接密码（默认为空）
        password: 
        # 连接超时时间
        timeout: 10s
        
# Dubbo
dubbo: 
    # 服务名 
    application: 
        name: dubbo-provider-demo
    # 扫描包 
    scan: 
        base-packages: com.pj
    # 注册中心地址 
    registry: 
        address: nacos://127.0.0.1:8001
    # 协议
    protocol: 
        name: dubbo
        port: 12345
        
        
        
        
        